//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_HomeworkSubmit
    {
        public int Id { get; set; }
        public string Answer { get; set; }
        public string Attachment { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<int> HomeworkId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<System.DateTime> SubmitDateTime { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> DealDateTime { get; set; }
        public string Score { get; set; }
        public string Remark { get; set; }
    }
}
