//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Info
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string ContentType { get; set; }
        public string Title { get; set; }
        public string Cover { get; set; }
        public string Abstract { get; set; }
        public string Content { get; set; }
        public string Resource { get; set; }
        public string Writer { get; set; }
        public string CreateIp { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string IsDeleted { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int SiteId { get; set; }
    }
}
