//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_LearningResource
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public string Attachment { get; set; }
        public string AttachmentName { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public int UserId { get; set; }
        public string MyURL { get; set; }
        public string MyURLName { get; set; }
        public Nullable<int> DownLoadCount { get; set; }
        public Nullable<int> SharedUserId { get; set; }
        public Nullable<long> SharedResourceId { get; set; }
        public string Remark { get; set; }
    }
}
