//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Project
    {
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string LearningTarget { get; set; }
        public string LearningImport { get; set; }
        public string TaskDescription { get; set; }
        public string TaskPrepare { get; set; }
        public string TaskImple { get; set; }
        public string ExtendedLearning { get; set; }
        public string ProjectGuidance { get; set; }
        public Nullable<int> SortIndex { get; set; }
        public string CreateIp { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string IsDeleted { get; set; }
        public Nullable<int> SiteId { get; set; }
    }
}
