//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Site
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Type { get; set; }
        public string Logo { get; set; }
        public string TopBanner { get; set; }
        public string Favicon { get; set; }
        public string Domain { get; set; }
        public string Status { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string AboutUs { get; set; }
        public string Helper { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public string FundSupport { get; set; }
        public string Technical { get; set; }
        public string Copyright { get; set; }
        public string Manual { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescription { get; set; }
        public string EnWeChat { get; set; }
        public string CourseIntroduce { get; set; }
        public string CreateIp { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string IsDeleted { get; set; }
        public int SiteId { get; set; }
        public string Title { get; set; }
    }
}
