//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EKP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int Id { get; set; }
        public string Account { get; set; }
        public string Status { get; set; }
        public string Type { get; set; }
        public string RealName { get; set; }
        public string PassWord { get; set; }
        public string Ips { get; set; }
        public Nullable<int> RoleId { get; set; }
        public string Email { get; set; }
        public string Photo { get; set; }
        public string Phone { get; set; }
        public string Telephone { get; set; }
        public string IDNumber { get; set; }
        public Nullable<int> Age { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Sex { get; set; }
        public Nullable<int> DrivingAge { get; set; }
        public Nullable<int> AllowCarType { get; set; }
        public Nullable<int> CarTestType { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public string Major { get; set; }
        public string ClassIds { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public string CreateIp { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string IsDeleted { get; set; }
        public int SiteId { get; set; }
        public string Attribute { get; set; }
        public string Education { get; set; }
    }
}
